name: Second Workflow
on: 
  push:
    branches:
      - 'SecondProject'

jobs:
  test:
    runs-on: ubuntu-latest 
    steps:
      - name: Get Code
        uses: actions/checkout@v3
        with:
          ref: SecondProject
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install npm dependencies
        run: npm ci
      - name: Run Tests
        run: npm test

        


